### ISSUE TITLE
全息显示在imipet身上是会时不时闪盔甲架

### ISSUE THREAD

**Issue by PIPILAN** [Arasple/TrHologram#12]
我问了下imipet作者，他说是全息图问题，宠物身上会时不时的闪出盔甲架，让我联系作者，所以我就来反馈了
动图：https://github.com/PIPILAN/IMG/raw/master/linshi/BUG.gif

**Comment by Arasple** [comment]
请提供一下你服务端的核心、版本

**Comment by PIPILAN** [comment]
服务器核心Paper1.14.4
