### ISSUE TITLE
1.14.4 Book editor doesnt work

### ISSUE THREAD

**Issue by GoldenGamerLP** [Arasple/TrHologram#16]
So when i type:
- /trhologram edit questHologramCircus
It gives me the book with title and text in it.. But when i edit the text and click done nothing changes..
There are no errors

**Comment by Tanguygab** [comment]
make sure that you did click on Done and not Sign

**Comment by GoldenGamerLP** [comment]
Yes i did

**Comment by GoldenGamerLP** [comment]
Ill make a video wait..

**Comment by Tanguygab** [comment]
does it change in the config?

**Comment by GoldenGamerLP** [comment]
The video ist uploading

**Comment by GoldenGamerLP** [comment]
Link:
- https://imgur.com/a/zZkBjlj

**Comment by GoldenGamerLP** [comment]
Ill checked the file.. nothing changed..

**Comment by GoldenGamerLP** [comment]
BTW Could you plase add a command to change all holograms view distances? Please... I have over 400 holograms + hologram files... that would take me hours

**Comment by GoldenGamerLP** [comment]
And ??
