### ISSUE TITLE
与 TrChat 同时使用会导致书本编辑时无法使用颜色代码&

### ISSUE THREAD

**Issue by Lanscarlos** [Arasple/TrHologram#18]
这个插件和 TrChat 一起使用会导致 你用书本编辑hd的时候无法弄颜色代码
使用书本时输入 "&+<颜色代码>" 时会自动变成 "搂+<颜色代码>"
例如 输入 "&aABC" 会变成 "搂aABC"
![2020-07-17_22 52 44](https://user-images.githubusercontent.com/67362486/87800727-51fb9500-c881-11ea-9ff6-bab907afa141.png)
![2020-07-17_22 52 41](https://user-images.githubusercontent.com/67362486/87800734-56c04900-c881-11ea-85f9-8cb4d007db0b.png)

个人的解决方法:
1. 删去TrChat （Tr系列的插件这么好用怎么舍得删？）
2. 直接在相应yml配置里用Alt+168打出§符号来改变颜色（没有书本编辑用的舒服QAQ）

**Comment by NTY666233** [comment]
出现同样问题 且在聊天中也会发生&被替换为搂的情况
