### ISSUE TITLE
TrHolo R2的问题

### ISSUE THREAD

**Issue by Score2** [Arasple/TrHologram#2]
目前玩家多次进出服务器全息图不显示BUG已被修复，但现在修出了一个问题：
- 玩家远离全息图直到全息图不显示后，再次回到viewDistance的范围全息图又将不会显示出来

**Comment by TSIXS** [comment]
补充：当距离全息图到达viewDistance设定的数值，再回到全息图旁边，又显示出来。我看了源代码，建议直接复制ListenerPlayerMove中的onMove的用法到ListenerPlayerJoin

**Comment by Arasple** [comment]
Fixed
