### ISSUE TITLE
SS-Kotlin incompatibility

### ISSUE THREAD

**Issue by pintoso** [Arasple/TrHologram#25]
The plugin stops working completely when used with [SS-Kotlin](https://github.com/SteveTheEngineer/SS-Kotlin) (it's a [SS-FancyDrop](https://www.spigotmc.org/resources/steves-series-fancy-drops.68373)'s dependency)

LOG: [click here](https://paste.gg/p/anonymous/b13684061b23468aaae1f9a77a99233e)

How to reproduce:
1. 1.16.x paper server
2. install [Trhologram](https://www.spigotmc.org/resources/trhologram-1-9-1-16.75503) + [SS-FancyDrops](https://www.spigotmc.org/resources/steves-series-fancy-drops.68373) + [SS-Kotlin](https://www.spigotmc.org/resources/steves-series-kotlin.89347)

>>Idk the source of the problem so I opened the issue in both places
the issue in ss-kotlin is [>HERE<](https://github.com/SteveTheEngineer/SS-Kotlin/issues/1)

**Comment by Arasple** [comment]
Fixed
Please download the latest actions build here https://github.com/Arasple/TrHologram/actions/runs/912113778
