### ISSUE TITLE
console error when creating a hologram in 1.8

### ISSUE THREAD

**Issue by Zarkness2** [Arasple/TrHologram#26]
I was testing the plugin in version 1.8 and when creating a hologram, it gives me an error in console and also does not create the hologram on the server but if I put /trhologram list I get that the hologram was created, I leave an image and pastebin of the error and that the hologram if it exists when I put /trhologram list

https://prnt.sc/10f7uva https://paste.helpch.at/inujewecop.sql https://prnt.sc/10f7xpy

**Comment by Arasple** [comment]
FlamePaper will not be supported
