### ISSUE TITLE
Warning on start and error on /trhd create xxxxx

### ISSUE THREAD

**Issue by oskarkk** [Arasple/TrHologram#27]
There is a java warning when I start the server, and when I try to use the plugin, it doesn't work.

Warning on server start:
https://paste.gg/p/anonymous/3f44364743a74b9c9ec270a0406b9851

Error when I try to use the plugin:
https://paste.gg/p/anonymous/7109d4b83aa34c8d93f855d3774c49c2

`This server is running Paper version git-Paper-543 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`

`System Info: Java 15 (OpenJDK 64-Bit Server VM 15.0.2+7) Host: Linux 5.10.13-2-MANJARO (amd64)`

**Comment by Arasple** [comment]
Fixed
Please download the latest actions build here https://github.com/Arasple/TrHologram/actions/runs/912113778
