### ISSUE TITLE
可视条件无法使用

### ISSUE THREAD

**Issue by xiangxiangxiong9** [Arasple/TrHologram#9]
#服务器信息 Paper 1.15.2 #137
#Trhologram版本 1.11
如题，我在用可视条件[行]时，仿照https://trhologram.trixey.cn/v/chinese/hologram/contents/options/condition 进行配置没有效果[我的ID为xiangxiangxiong，我很少会上GitHub，可能需要联系QQ 1296976552]
[涉及行的其中之一:Line11: - '§atest<condition:"%player_name%" == "EditEgg">']
@Arasple

**Comment by Arasple** [comment]
尝试添加<update>标签, 提供全息行一个更新周期

**Comment by xiangxiangxiong9** [comment]
我在那一行添加了<update:1>，但是没有效果……
[或许你可以连接服务器？]
